collectibles:
  albums:
    - id: 1
      name: "Animals"
      cards:
        - id: : 1
          name: "Eagle"
        - id: 2
          name: "Cormorant"
        - id: 3
          name: "Sparrow"
        - id: 4
          name: "Raven"
        - id: 5
          name: "Salmon"
        - id: 6
          name: "Mullet"
        - id: 7
          name: "Bream"
        - id: 8
          name: "Marline"